
-----------------------------------Ready: P1 P2 P3 
-----------------------------------Waiting: 
-----------------------------------Terminated: 
P1 rel R1: error nothing to release
P1 terminated

-----------------------------------Running on kernel thread 0: P1 
-----------------------------------Ready: P2 P3 
-----------------------------------Waiting: 
-----------------------------------Terminated: P1 
P2 rel R2: error nothing to release
P2 terminated

-----------------------------------Running on kernel thread 0: P2 
-----------------------------------Ready: P3 
-----------------------------------Waiting: 
-----------------------------------Terminated: P1 P2 
P3 rel R3: error nothing to release
P3 terminated

-----------------------------------Running on kernel thread 0: P3 
-----------------------------------Ready: 
-----------------------------------Waiting: 
-----------------------------------Terminated: P1 P2 P3 

-----------------------------------Ready: 
-----------------------------------Waiting: 
-----------------------------------Terminated: P1 P2 P3 
