
-----------------------------------Ready: P1 P2 P3 
-----------------------------------Waiting: 
-----------------------------------Terminated: 
P1 req R1: acquired
Available: R1 R1 

-----------------------------------Running on kernel thread 0: P1 
-----------------------------------Ready: P2 P3 
-----------------------------------Waiting: 
-----------------------------------Terminated: 
P1 rel R1: released
Available: R1 R1 R1 
P1 terminated

-----------------------------------Running on kernel thread 0: P1 
-----------------------------------Ready: P2 P3 
-----------------------------------Waiting: 
-----------------------------------Terminated: P1 
P2 req R1: acquired
Available: R1 R1 

-----------------------------------Running on kernel thread 0: P2 
-----------------------------------Ready: P3 
-----------------------------------Waiting: 
-----------------------------------Terminated: P1 
P2 rel R1: released
Available: R1 R1 R1 
P2 terminated

-----------------------------------Running on kernel thread 0: P2 
-----------------------------------Ready: P3 
-----------------------------------Waiting: 
-----------------------------------Terminated: P1 P2 
P3 req R1: acquired
Available: R1 R1 

-----------------------------------Running on kernel thread 0: P3 
-----------------------------------Ready: 
-----------------------------------Waiting: 
-----------------------------------Terminated: P1 P2 
P3 rel R1: released
Available: R1 R1 R1 
P3 terminated

-----------------------------------Running on kernel thread 0: P3 
-----------------------------------Ready: 
-----------------------------------Waiting: 
-----------------------------------Terminated: P1 P2 P3 

-----------------------------------Ready: 
-----------------------------------Waiting: 
-----------------------------------Terminated: P1 P2 P3 
