
-----------------------------------Ready: P1 
-----------------------------------Waiting: 
-----------------------------------Terminated: 
P1 req R1: acquired
Available: R2 R2 R3 R4 
New arrivals in ready queue: P2 P2: ready
P1: ready

-----------------------------------Running on kernel thread 0: P1 
-----------------------------------Ready: P2 P1 
-----------------------------------Waiting: 
-----------------------------------Terminated: 
P2 req R2: acquired
Available: R2 R3 R4 
New arrivals in ready queue: P3 P3: ready
P2: ready

-----------------------------------Running on kernel thread 0: P2 
-----------------------------------Ready: P1 P3 P2 
-----------------------------------Waiting: 
-----------------------------------Terminated: 
P3 req R2: acquired
Available: R3 R4 
New arrivals in ready queue: P6 P6: ready
P3: ready

-----------------------------------Running on kernel thread 0: P3 
-----------------------------------Ready: P1 P2 P6 P3 
-----------------------------------Waiting: 
-----------------------------------Terminated: 
P6: no instruction to execute
P6 terminated
New arrivals in ready queue: P7 P7: ready
P7: no instruction to execute
P7 terminated
New arrivals in ready queue: P4 P4: ready
P4 req R3: acquired
Available: R4 
New arrivals in ready queue: P5 P5: ready
P4: ready

-----------------------------------Running on kernel thread 0: P4 
-----------------------------------Ready: P1 P2 P3 P5 P4 
-----------------------------------Waiting: 
-----------------------------------Terminated: P6 P7 
P5 req R4: acquired
Available: 

-----------------------------------Running on kernel thread 0: P5 
-----------------------------------Ready: P1 P2 P3 P4 
-----------------------------------Waiting: 
-----------------------------------Terminated: P6 P7 
P5 rel R4: released
Available: R4 
P5 terminated

-----------------------------------Running on kernel thread 0: P5 
-----------------------------------Ready: P1 P2 P3 P4 
-----------------------------------Waiting: 
-----------------------------------Terminated: P6 P7 P5 
P4 req R2: waiting

-----------------------------------Running on kernel thread 0: P4 
-----------------------------------Ready: P1 P2 P3 
-----------------------------------Waiting: P4 
-----------------------------------Terminated: P6 P7 P5 
P3 req R3: waiting

-----------------------------------Running on kernel thread 0: P3 
-----------------------------------Ready: P1 P2 
-----------------------------------Waiting: P4 P3 
-----------------------------------Terminated: P6 P7 P5 
P2 req R1: waiting

-----------------------------------Running on kernel thread 0: P2 
-----------------------------------Ready: P1 
-----------------------------------Waiting: P4 P3 P2 
-----------------------------------Terminated: P6 P7 P5 
P1 req R2: waiting

-----------------------------------Running on kernel thread 0: P1 
-----------------------------------Ready: 
-----------------------------------Waiting: P4 P3 P2 P1 
-----------------------------------Terminated: P6 P7 P5 
Deadlock detected:Deadlock detected:
-----------------------------------Ready: 
-----------------------------------Waiting: P4 P3 P2 P1 
-----------------------------------Terminated: P6 P7 P5 
