
-----------------------------------Ready: P1 P2 P3 
-----------------------------------Waiting: 
-----------------------------------Terminated: 
P3: unknown instruction
P3 terminated

-----------------------------------Running on kernel thread 0: P3 
-----------------------------------Ready: P1 P2 
-----------------------------------Waiting: 
-----------------------------------Terminated: P3 
P1 req R1: acquired
Available: R2 

-----------------------------------Running on kernel thread 0: P1 
-----------------------------------Ready: P2 
-----------------------------------Waiting: 
-----------------------------------Terminated: P3 
P1 rel R1: released
Available: R1 R2 

-----------------------------------Running on kernel thread 0: P1 
-----------------------------------Ready: P2 
-----------------------------------Waiting: 
-----------------------------------Terminated: P3 
P1 req R2: acquired
Available: R1 

-----------------------------------Running on kernel thread 0: P1 
-----------------------------------Ready: P2 
-----------------------------------Waiting: 
-----------------------------------Terminated: P3 
P1 rel R2: released
Available: R1 R2 
P1 terminated

-----------------------------------Running on kernel thread 0: P1 
-----------------------------------Ready: P2 
-----------------------------------Waiting: 
-----------------------------------Terminated: P3 P1 
P2: unknown instruction
P2 terminated

-----------------------------------Running on kernel thread 0: P2 
-----------------------------------Ready: 
-----------------------------------Waiting: 
-----------------------------------Terminated: P3 P1 P2 

-----------------------------------Ready: 
-----------------------------------Waiting: 
-----------------------------------Terminated: P3 P1 P2 
