
-----------------------------------Ready: P1 P2 P3 
-----------------------------------Waiting: 
-----------------------------------Terminated: 
P1 req R1: acquired
Available: R2 
New arrivals in ready queue: P4 P4: ready

-----------------------------------Running on kernel thread 0: P1 
-----------------------------------Ready: P2 P3 P4 
-----------------------------------Waiting: 
-----------------------------------Terminated: 
P1 rel R1: released
Available: R1 R2 
New arrivals in ready queue: P5 P5: ready
P1: ready

-----------------------------------Running on kernel thread 0: P1 
-----------------------------------Ready: P2 P3 P4 P5 P1 
-----------------------------------Waiting: 
-----------------------------------Terminated: 
P2 req R1: acquired
Available: R2 
New arrivals in ready queue: P6 P6: ready

-----------------------------------Running on kernel thread 0: P2 
-----------------------------------Ready: P3 P4 P5 P1 P6 
-----------------------------------Waiting: 
-----------------------------------Terminated: 
P2 req R2: acquired
Available: 
P2: ready

-----------------------------------Running on kernel thread 0: P2 
-----------------------------------Ready: P3 P4 P5 P1 P6 P2 
-----------------------------------Waiting: 
-----------------------------------Terminated: 
P3 req R1: waiting

-----------------------------------Running on kernel thread 0: P3 
-----------------------------------Ready: P4 P5 P1 P6 P2 
-----------------------------------Waiting: P3 
-----------------------------------Terminated: 
P4: no instruction to execute
P4 terminated
P5: no instruction to execute
P5 terminated
P1 req R2: waiting

-----------------------------------Running on kernel thread 0: P1 
-----------------------------------Ready: P6 P2 
-----------------------------------Waiting: P3 P1 
-----------------------------------Terminated: P4 P5 
P6: no instruction to execute
P6 terminated
P2 rel R1: released
Available: R1 
Wake up process P3 waiting for R1
P3: ready

-----------------------------------Running on kernel thread 0: P2 
-----------------------------------Ready: P3 
-----------------------------------Waiting: P1 
-----------------------------------Terminated: P4 P5 P6 
P2 rel R2: released
Available: R1 R2 
Wake up process P1 waiting for R2
P1: ready
P2 terminated

-----------------------------------Running on kernel thread 0: P2 
-----------------------------------Ready: P3 P1 
-----------------------------------Waiting: 
-----------------------------------Terminated: P4 P5 P6 P2 
P3 req R1: acquired
Available: R2 

-----------------------------------Running on kernel thread 0: P3 
-----------------------------------Ready: P1 
-----------------------------------Waiting: 
-----------------------------------Terminated: P4 P5 P6 P2 
P3 req R2: acquired
Available: 
P3: ready

-----------------------------------Running on kernel thread 0: P3 
-----------------------------------Ready: P1 P3 
-----------------------------------Waiting: 
-----------------------------------Terminated: P4 P5 P6 P2 
P1 req R2: waiting

-----------------------------------Running on kernel thread 0: P1 
-----------------------------------Ready: P3 
-----------------------------------Waiting: P1 
-----------------------------------Terminated: P4 P5 P6 P2 
P3 rel R1: released
Available: R1 

-----------------------------------Running on kernel thread 0: P3 
-----------------------------------Ready: 
-----------------------------------Waiting: P1 
-----------------------------------Terminated: P4 P5 P6 P2 
P3 rel R2: released
Available: R1 R2 
Wake up process P1 waiting for R2
P1: ready
P3 terminated

-----------------------------------Running on kernel thread 0: P3 
-----------------------------------Ready: P1 
-----------------------------------Waiting: 
-----------------------------------Terminated: P4 P5 P6 P2 P3 
P1 req R2: acquired
Available: R1 

-----------------------------------Running on kernel thread 0: P1 
-----------------------------------Ready: 
-----------------------------------Waiting: 
-----------------------------------Terminated: P4 P5 P6 P2 P3 
P1 rel R2: released
Available: R1 R2 
P1 terminated

-----------------------------------Running on kernel thread 0: P1 
-----------------------------------Ready: 
-----------------------------------Waiting: 
-----------------------------------Terminated: P4 P5 P6 P2 P3 P1 

-----------------------------------Ready: 
-----------------------------------Waiting: 
-----------------------------------Terminated: P4 P5 P6 P2 P3 P1 
