P1 req R1: acquired
P4: ready
P1 rel R1: released
P5: ready
P1: ready
P2 req R1: acquired
P6: ready
P2 req R2: acquired
P2: ready
P3 req R1: waiting
P1 req R2: waiting
P2 rel R1: released
Wake up process P3 waiting for R1
P3: ready
P2 rel R2: released
Wake up process P1 waiting for R2
P1: ready
P3 req R1: acquired
P3 req R2: acquired
P3: ready
P1 req R2: waiting
P3 rel R1: released
P3 rel R2: released
Wake up process P1 waiting for R2
P1: ready
P1 req R2: acquired
P1 rel R2: released
