
-----------------------------------Ready: P1 
-----------------------------------Waiting: 
-----------------------------------Terminated: 
P1 req R1: acquired
Available: 
New arrivals in ready queue: P2 P2: ready

-----------------------------------Running on kernel thread 0: P1 
-----------------------------------Ready: P2 
-----------------------------------Waiting: 
-----------------------------------Terminated: 
P1 rel R1: released
Available: R1 
P1 terminated

-----------------------------------Running on kernel thread 0: P1 
-----------------------------------Ready: P2 
-----------------------------------Waiting: 
-----------------------------------Terminated: P1 
P2 req R1: acquired
Available: 

-----------------------------------Running on kernel thread 0: P2 
-----------------------------------Ready: 
-----------------------------------Waiting: 
-----------------------------------Terminated: P1 
P2 rel R1: released
Available: R1 
P2 terminated

-----------------------------------Running on kernel thread 0: P2 
-----------------------------------Ready: 
-----------------------------------Waiting: 
-----------------------------------Terminated: P1 P2 

-----------------------------------Ready: 
-----------------------------------Waiting: 
-----------------------------------Terminated: P1 P2 
