
-----------------------------------Ready: P1 
-----------------------------------Waiting: 
-----------------------------------Terminated: 
P1 req R1: acquired
Available: 
New arrivals in ready queue: P2 P2: ready
P1 rel R1: released
Available: R1 
P1 terminated
P2 req R1: acquired
Available: 
P2 rel R1: released
Available: R1 
P2 terminated

-----------------------------------Ready: 
-----------------------------------Waiting: 
-----------------------------------Terminated: P1 P2 
